### ISSUE TITLE
Docker-compose showing Error while resolving packages

### ISSUE THREAD

**Issue by iqbalpb01** [calcom/docker#103]
Using latest version of docker and docker-compose

## Error
Screenshot
[https://raw.githubusercontent.com/iqbalpb01/Hacktopress/master/Screenshot%20from%202022-04-22%2015-13-04.png](url)

`error Couldn't find package "@calcom/app-store@*" required by "@calcom/web@1.5.2" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find package "@calcom/ee@*" required by "@calcom/web@1.5.2" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/opt/yarn-v1.22.17/lib/cli.js:721:66)
    at new MessageError (/opt/yarn-v1.22.17/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/opt/yarn-v1.22.17/lib/cli.js:36582:17)
    at Generator.throw (<anonymous>)
    at step (/opt/yarn-v1.22.17/lib/cli.js:310:30)
    at /opt/yarn-v1.22.17/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Error: Couldn't find package "@calcom/core@*" required by "@calcom/web@1.5.2" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/opt/yarn-v1.22.17/lib/cli.js:721:66)
    at new MessageError (/opt/yarn-v1.22.17/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/opt/yarn-v1.22.17/lib/cli.js:36582:17)
    at Generator.throw (<anonymous>)
    at step (/opt/yarn-v1.22.17/lib/cli.js:310:30)
    at /opt/yarn-v1.22.17/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Error: Couldn't find package "@calcom/stripe@*" required by "@calcom/web@1.5.2" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/opt/yarn-v1.22.17/lib/cli.js:721:66)
    at new MessageError (/opt/yarn-v1.22.17/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/opt/yarn-v1.22.17/lib/cli.js:36582:17)
    at Generator.throw (<anonymous>)
    at step (/opt/yarn-v1.22.17/lib/cli.js:310:30)
    at /opt/yarn-v1.22.17/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Error: Couldn't find package "@calcom/config@*" required by "@calcom/web@1.5.2" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/opt/yarn-v1.22.17/lib/cli.js:721:66)
    at new MessageError (/opt/yarn-v1.22.17/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/opt/yarn-v1.22.17/lib/cli.js:36582:17)
    at Generator.throw (<anonymous>)
    at step (/opt/yarn-v1.22.17/lib/cli.js:310:30)
    at /opt/yarn-v1.22.17/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Error: Couldn't find package "@calcom/ui@*" required by "@calcom/web@1.5.2" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/opt/yarn-v1.22.17/lib/cli.js:721:66)
    at new MessageError (/opt/yarn-v1.22.17/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/opt/yarn-v1.22.17/lib/cli.js:36582:17)
    at Generator.throw (<anonymous>)
    at step (/opt/yarn-v1.22.17/lib/cli.js:310:30)
    at /opt/yarn-v1.22.17/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Error: Couldn't find package "@calcom/types@*" required by "@calcom/web@1.5.2" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/opt/yarn-v1.22.17/lib/cli.js:721:66)
    at new MessageError (/opt/yarn-v1.22.17/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/opt/yarn-v1.22.17/lib/cli.js:36582:17)
    at Generator.throw (<anonymous>)
    at step (/opt/yarn-v1.22.17/lib/cli.js:310:30)
    at /opt/yarn-v1.22.17/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
`

**Comment by krumware** [comment]
can you please retry with the latest images?

**Comment by krumware** [comment]
closing for inactivity
