### ISSUE TITLE
docker compose build fail

### ISSUE THREAD

**Issue by sjcotto** [calcom/docker#113]
hi there, was trying to install the docker-compose "as is" without any change but it's giving the following error

@calcom/prisma:build: error: Environment variable not found: DATABASE_URL.
@calcom/prisma:build:   -->  schema.prisma:6
@calcom/prisma:build:    | 
@calcom/prisma:build:  5 |   provider = "postgresql"
@calcom/prisma:build:  6 |   url      = env("DATABASE_URL")
@calcom/prisma:build:    | 
@calcom/prisma:build: 
@calcom/prisma:build: Validation Error Count: 1
@calcom/prisma:build: 

not sure if the solution will be to add the DATABASE_URL into the ARG of the Dockerfile

anyone can help?

**Comment by apitel** [comment]
I am having the same issue

**Comment by kaddour-youcef** [comment]
Anyone found a solution ?

**Comment by theRealBithive** [comment]
@kaddour-youcef here is a repo that builds from the non docker files and creates a docker container: https://github.com/speckm/calendso-docker

**Comment by SebastiaanVanspauwen** [comment]
Facing the same issue

**Comment by krumware** [comment]
If possible, please try the changes in #112.
Prior to building, you can run `docker compose up -d database`, to make a database available, then use `host.docker.internal` as the hostname for the DATABASE_URL arg, and that will successfully validate the prisma schemas. Afterwards you can change your database host back to the desired runtime database.

**Comment by Th0masDB** [comment]
> @kaddour-youcef here is a repo that builds from the non docker files and creates a docker container: https://github.com/speckm/calendso-docker

This doesn't work unfortunately.

**Comment by SebastiaanVanspauwen** [comment]
@Th0masDB #112 worked for me

**Comment by Th0masDB** [comment]
> @Th0masDB #112 worked for me

Unfortuanly for me it doesn't.... It makes the container.... But the container won't run with this error (but I think this is another topic):
```
/calcom/scripts/start.sh:4

scripts/wait-for-it.sh ${DATABASE_HOST} -- echo "database is up"

             ^^^

SyntaxError: Unexpected token 'for'

    at wrapSafe (internal/modules/cjs/loader.js:1001:16)

    at Module._compile (internal/modules/cjs/loader.js:1049:27)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

    at Module.load (internal/modules/cjs/loader.js:950:32)

    at Function.Module._load (internal/modules/cjs/loader.js:790:12)

    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)

    at internal/main/run_main_module.js:17:47
```

**Comment by kaddour-youcef** [comment]
I dont know about the docker it did not work, but you can build it from the repo it worked for me!

**Comment by varghesevisal** [comment]
This issue even exists today.

Prisma schema loaded from schema.prisma
36.82 @calcom/prisma:post-install: Formatted /app/packages/prisma/schema.prisma in 178ms 🚀
37.18 @calcom/prisma:build: cache bypass, force executing 48912e58258dab66
39.92 @calcom/prisma:build: No DATABASE_URL found, skipping migrations
40.00 @calcom/api:build: cache miss, executing 7fa1bf89949b74e8
43.97 @calcom/api:build: `destination` does not start with `/`, `http://`, or `https://` for route {"source":"/api/v2","destination":"undefined/health"}
43.97 @calcom/api:build: 
43.97 @calcom/api:build: `destination` does not start with `/`, `http://`, or `https://` for route {"source":"/api/v2/health","destination":"undefined/health"}
43.97 @calcom/api:build: 
43.97 @calcom/api:build: `destination` does not start with `/`, `http://`, or `https://` for route {"source":"/api/v2/docs/:path*","destination":"undefined/docs/:path*"}
43.97 @calcom/api:build: 
43.97 @calcom/api:build: `destination` does not start with `/`, `http://`, or `https://` for route {"source":"/api/v2/:path*","destination":"undefined/api/v2/:path*"}
43.97 @calcom/api:build: 
43.97 @calcom/api:build: 
43.97 @calcom/api:build: Error: Invalid rewrites found
44.03 @calcom/api:build: ERROR: command finished with error: command (/app/apps/api/v1) yarn run build exited (1)
44.03 command (/app/apps/api/v1) yarn run build exited (1)
44.03 
44.03  Tasks:    2 successful, 3 total
44.03 Cached:    0 cached, 3 total
44.03   Time:    39.812s 
44.03 Failed:    @calcom/api#build
44.03 
44.03  ERROR  run failed: command  exited (1)
