### ISSUE TITLE
SyntaxError: Unexpected token 'for'

### ISSUE THREAD

**Issue by Th0masDB** [calcom/docker#123]
When I was installing calcom for the first time, I got this error (I used this `DOCKER_BUILDKIT=0 docker compose build calcom` to build it):

```
/calcom/scripts/start.sh:4
scripts/wait-for-it.sh ${DATABASE_HOST} -- echo "database is up"
             ^^^

SyntaxError: Unexpected token 'for'
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by krumware** [comment]
I'm unable to replicate the issue.
Can you please updating line 4 of start.sh to `./scripts/wait-for-it.sh ${DATABASE_HOST} -- echo "database is up"`
(add the beginning ./)

**Comment by Mistic92** [comment]
I have the same issue. I tried to rename script to remove for but now I get 
```
 /calcom/scripts/start.sh:4
calcom-docker-calcom-1  | scripts/wait_it.sh ${DATABASE_HOST} -- echo "database is up"
calcom-docker-calcom-1  |                            ^
calcom-docker-calcom-1  | 
calcom-docker-calcom-1  | SyntaxError: Unexpected identifier
```

**Comment by krumware** [comment]
Closing for cleanup. This may be addressed by incoming updates.
