### ISSUE TITLE
Error: Could not find a production build in the '/calcom/apps/web/.next' directory

### ISSUE THREAD

**Issue by Xosten** [calcom/docker#155]
Hi,

After having followed the guide to setup the docker container and build the image. When starting the container with `docker compose up -d`. I get the following error : 

````
calcom-docker-calcom-1  | @calcom/web:start: $ next start
calcom-docker-calcom-1  | @calcom/web:start: ready - started server on 0.0.0.0:3000, url: http://localhost:3000
calcom-docker-calcom-1  | @calcom/web:start: Error: Could not find a production build in the '/calcom/apps/web/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
calcom-docker-calcom-1  | @calcom/web:start:     at NextNodeServer.getBuildId (/calcom/node_modules/next/dist/server/next-server.js:116:23)
calcom-docker-calcom-1  | @calcom/web:start:     at new Server (/calcom/node_modules/next/dist/server/base-server.js:70:29)
calcom-docker-calcom-1  | @calcom/web:start:     at new NextNodeServer (/calcom/node_modules/next/dist/server/next-server.js:63:9)
calcom-docker-calcom-1  | @calcom/web:start:     at NextServer.createServer (/calcom/node_modules/next/dist/server/next.js:140:16)
calcom-docker-calcom-1  | @calcom/web:start:     at async /calcom/node_modules/next/dist/server/next.js:149:31
calcom-docker-calcom-1  | @calcom/web:start: error Command failed with exit code 1.
calcom-docker-calcom-1  | @calcom/web:start: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
calcom-docker-calcom-1  | @calcom/web:start: ERROR: command finished with error: command (apps/web) yarn run start exited (1)
calcom-docker-calcom-1  | command (apps/web) yarn run start exited (1)
calcom-docker-calcom-1  | 
calcom-docker-calcom-1  |  Tasks:    1 successful, 2 total
calcom-docker-calcom-1  | Cached:    0 cached, 2 total
calcom-docker-calcom-1  |   Time:    8.507s 
calcom-docker-calcom-1  | 
calcom-docker-calcom-1  | error Command failed with exit code 1.
calcom-docker-calcom-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
calcom-docker-calcom-1 exited with code 0
````

I've notice #152 has the same issue as I have.

**Comment by PeerRich** [comment]
@krumware any ideas?

**Comment by Xosten** [comment]
Hey,

I have retried building the image after a week and everything seems to work now. I don't have any ideas how it got fixed... 

Closing for now.
