### ISSUE TITLE
Unable to access login page after initial login

### ISSUE THREAD

**Issue by PaulTimmermann** [calcom/docker#220]
Hallo, I set up calcom yesterday and everything was working perfectly until I tried to login with another device.
I am getting the error 500 page as I visit the /auth/login page.
![grafik](https://user-images.githubusercontent.com/63471946/220899516-826ca036-4d27-4d55-b296-ab1711c7b329.png)
I checked folder permissions. I suppose it might be something with my reverse proxy but to be honest I have no clue.
The container logs of the calcom container print:

```
@calcom/web:start: Error: Pass an absolute URL

@calcom/web:start:     at getSafeRedirectUrl (/calcom/apps/web/.next/server/chunks/917.js:21071:15)

@calcom/web:start:     at Login (/calcom/apps/web/.next/server/pages/auth/login.js:500:121)

@calcom/web:start:     at Wc (/calcom/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)

@calcom/web:start:     at Zc (/calcom/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)

@calcom/web:start:     at Z (/calcom/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)

@calcom/web:start:     at $c (/calcom/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)

@calcom/web:start:     at bd (/calcom/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)

@calcom/web:start:     at Z (/calcom/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)

@calcom/web:start:     at Zc (/calcom/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)

@calcom/web:start:     at Z (/calcom/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)

@calcom/web:start:     at Zc (/calcom/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)

@calcom/web:start:     at Z (/calcom/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)

@calcom/web:start:     at $c (/calcom/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)

@calcom/web:start:     at bd (/calcom/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)

@calcom/web:start:     at Z (/calcom/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)

@calcom/web:start:     at Zc (/calcom/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
```
Anyone an idea?

Best regards 
Paul

**Comment by PaulTimmermann** [comment]
```
NODE_TLS_REJECT_UNAUTHORIZED=0 
```
Fixed the Issue
