### ISSUE TITLE
Caldav : issue with Invalid key length caldav despite "dd if=/dev/urandom bs=1K count=1 | md5sum"

### ISSUE THREAD

**Issue by TheLazyGeekGuy** [calcom/docker#222]
Hello,

CALENDSO_ENCRYPTION_KEY was generated by `dd if=/dev/urandom bs=1K count=1 | md5sum` on mac terminal

after multiple generation : still the issue is there while adding caldav 

```
@calcom/web:start: RangeError: Invalid key length

@calcom/web:start:     at Cipheriv.createCipherBase (node:internal/crypto/cipher:116:19)

@calcom/web:start:     at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:135:3)

@calcom/web:start:     at new Cipheriv (node:internal/crypto/cipher:243:3)

@calcom/web:start:     at Object.createCipheriv (node:crypto:138:10)

@calcom/web:start:     at symmetricEncrypt (/calcom/apps/web/.next/server/chunks/1096.js:29:66)

@calcom/web:start:     at handler (/calcom/apps/web/.next/server/chunks/7105.js:277:95)

@calcom/web:start:     at async handler (/calcom/apps/web/.next/server/pages/api/integrations/[...args].js:600:13)

@calcom/web:start:     at async Object.apiResolver (/calcom/node_modules/next/dist/server/api-utils/node.js:363:9)

@calcom/web:start:     at async NextNodeServer.runApi (/calcom/node_modules/next/dist/server/next-server.js:487:9)

@calcom/web:start:     at async Object.fn (/calcom/node_modules/next/dist/server/next-server.js:749:37)

@calcom/web:start:     at async Router.execute (/calcom/node_modules/next/dist/server/router.js:253:36)

@calcom/web:start:     at async NextNodeServer.run (/calcom/node_modules/next/dist/server/base-server.js:384:29)

@calcom/web:start:     at async NextNodeServer.handleRequest (/calcom/node_modules/next/dist/server/base-server.js:322:20) {

@calcom/web:start:   code: 'ERR_CRYPTO_INVALID_KEYLEN'

@calcom/web:start: }

```

Did i missed something ?

**Comment by TheLazyGeekGuy** [comment]
Solved : don't use quote with the key !
