### ISSUE TITLE
 @calcom/google-tag-manager package doesn't seem to be present on trying to build calcom container.

### ISSUE THREAD

**Issue by deepushajia** [calcom/docker#234]
@calcom/google-tag-manager@workspace:packages/app-store/google-tag-manager: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile

**Comment by TD-INFRANFC** [comment]
Same problem 👍

**Comment by luizeof** [comment]
Same here:

![cd2e9a4d-c6e7-42fc-b92c-146c79e141a0](https://user-images.githubusercontent.com/257004/230662352-6136719f-0197-41e4-91fa-cbb4e31a9846.png)

**Comment by krumware** [comment]
Checking on this

**Comment by anishg24** [comment]
Tried updating `scripts/start.sh` to add an extra `yarn install` but I don't think docker is picking up my changes (after rebuilding and restarting)

**Comment by krumware** [comment]
This is something that needs to be addressed in cal.com core. Eyes are on it, sorry for the inconvenience

**Comment by anandchristudas** [comment]
Yes, I have the same issue. Not able to make cal.com up and running using both the (Most users) method and the (Advanced users) method.

In (Most users) method the docker compose up -d calcom gets executed successfully but the docker is crashing within 1 min.

In (Advanced users) method the docker compose up -d ends at the 14th step always.

**Comment by eleith** [comment]
```
diff --git a/yarn.lock b/yarn.lock
index ef4d01537..58fdd796e 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -3947,6 +3947,16 @@ __metadata:
   languageName: unknown
   linkType: soft

+"@calcom/google-tag-manager@workspace:packages/app-store/google-tag-manager":
+  version: 0.0.0-use.local
+  resolution: "@calcom/google-tag-manager@workspace:packages/app-store/google-tag-manager"
+  dependencies:
+    "@calcom/prisma": "*"
+    "@calcom/types": "*"
+    react-hook-form: ^7.43.3
+  languageName: unknown
+  linkType: soft
+
 "@calcom/around@workspace:packages/app-store/around":
   version: 0.0.0-use.local
   resolution: "@calcom/around@workspace:packages/app-store/around"
```

the above patch to `yarn.lock` will resolve the issue until this is fixed upstream.

**Comment by krumware** [comment]
upstream yarn.lock had an update two days ago which added google-tag-manager to the yarn.lock. Just confirming, Is this still breaking for you after pulling latest `main` in the submodule?

**Comment by eleith** [comment]
@krumware , thanks for the heads up, i can confirm, it build/works for me.

**Comment by ahmed-kino** [comment]
I pulled the latest main and I'm still having the issue, am I missing something?

**Comment by abdallahalsamman** [comment]
@krumware issue still here for me

```
machine@machines-MacBook-Pro docker-calcom % git reset --hard head   
HEAD is now at cb9db89 Auto updated submodule references
machine@machines-MacBook-Pro docker-calcom % git pull
Already up to date.
machine@machines-MacBook-Pro docker-calcom % cp .env.example .env

machine@machines-MacBook-Pro docker-calcom % docker compose pull

[+] Running 3/3
 ⠿ studio Skipped - Image is already being pulled by calcom                                                                                                                                          0.0s
 ⠿ calcom Pulled                                                                                                                                                                                     5.0s
 ⠿ database Pulled                                                                                                                                                                                   3.5s
machine@machines-MacBook-Pro docker-calcom % docker compose up calcom
[+] Running 3/3
 ⠿ Network stack                     Created                                                                                                                                                         0.1s
 ⠿ Container database                Created                                                                                                                                                         0.2s
 ⠿ Container docker-calcom-calcom-1  Created                                                                                                                                                         0.1s
Attaching to docker-calcom-calcom-1
docker-calcom-calcom-1  | Nothing to replace, the value is already set to http://localhost:3000.
docker-calcom-calcom-1  | + scripts/replace-placeholder.sh http://localhost:3000 http://localhost:3000
docker-calcom-calcom-1  | + scripts/wait-for-it.sh database:5432 -- echo database is up
docker-calcom-calcom-1  | nc command is missing!
docker-calcom-calcom-1  | + npx prisma migrate deploy --schema /calcom/packages/prisma/schema.prisma
docker-calcom-calcom-1  | Prisma schema loaded from packages/prisma/schema.prisma
docker-calcom-calcom-1  | Datasource "db": PostgreSQL database "calendso", schema "public" at "database:5432"
docker-calcom-calcom-1  | 
docker-calcom-calcom-1  | 167 migrations found in prisma/migrations
docker-calcom-calcom-1  | 
docker-calcom-calcom-1  | 
docker-calcom-calcom-1  | No pending migrations to apply.
docker-calcom-calcom-1  | + npx ts-node --transpile-only /calcom/packages/prisma/seed-app-store.ts
docker-calcom-calcom-1  | 📲 Upserted app: 'apple-calendar'
docker-calcom-calcom-1  | 📲 Upserted app: 'caldav-calendar'
docker-calcom-calcom-1  | Error adding google credentials to DB: Cannot destructure property 'client_secret' of 'JSON.parse(...).web' as it is undefined.
docker-calcom-calcom-1  | 📲 Upserted app: 'jitsi'
docker-calcom-calcom-1  | 📲 Upserted app: 'sylaps'
docker-calcom-calcom-1  | 📲 Upserted app: 'wipe-my-cal'
docker-calcom-calcom-1  | 📲 Upserted app: 'huddle01'
docker-calcom-calcom-1  | 📲 Upserted app: 'routing-forms'
docker-calcom-calcom-1  | 📲 Upserted app: 'whereby'
docker-calcom-calcom-1  | 📲 Upserted app: 'around'
docker-calcom-calcom-1  | 📲 Upserted app: 'riverside'
docker-calcom-calcom-1  | 📲 Upserted app: 'typeform'
docker-calcom-calcom-1  | 📲 Upserted app: 'ping'
docker-calcom-calcom-1  | 📲 Upserted app: 'campfire'
docker-calcom-calcom-1  | 📲 Upserted app: 'rainbow'
docker-calcom-calcom-1  | 📲 Upserted app: 'raycast'
docker-calcom-calcom-1  | 📲 Upserted app: 'n8n'
docker-calcom-calcom-1  | 📲 Upserted app: 'exchange'
docker-calcom-calcom-1  | 📲 Upserted app: 'qr_code'
docker-calcom-calcom-1  | 📲 Upserted app: 'weather_in_your_calendar'
docker-calcom-calcom-1  | 📲 Upserted app: 'fathom'
docker-calcom-calcom-1  | 📲 Upserted app: 'plausible'
docker-calcom-calcom-1  | 📲 Upserted app: 'wordpress'
docker-calcom-calcom-1  | 📲 Upserted app: 'ga4'
docker-calcom-calcom-1  | 📲 Upserted app: 'pipedream'
docker-calcom-calcom-1  | 📲 Upserted app: 'sirius_video'
docker-calcom-calcom-1  | 📲 Upserted app: 'sendgrid'
docker-calcom-calcom-1  | 📲 Upserted app: 'closecom'
docker-calcom-calcom-1  | 📲 Upserted app: 'whatsapp'
docker-calcom-calcom-1  | 📲 Upserted app: 'telegram'
docker-calcom-calcom-1  | 📲 Upserted app: 'signal'
docker-calcom-calcom-1  | 📲 Upserted app: 'vimcal'
docker-calcom-calcom-1  | 📲 Upserted app: 'amie'
docker-calcom-calcom-1  | 📲 Upserted app: 'facetime'
docker-calcom-calcom-1  | 📲 Upserted app: 'zohocrm'
docker-calcom-calcom-1  | 📲 Upserted app: 'cron'
docker-calcom-calcom-1  | 📲 Upserted app: 'google-tag-manager'
docker-calcom-calcom-1  | Skipping Routing Form - Seeding - Pro User not found
docker-calcom-calcom-1  | + yarn start
docker-calcom-calcom-1  | Internal Error: @calcom/google-tag-manager@workspace:packages/app-store/google-tag-manager: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
docker-calcom-calcom-1  |     at P0.getCandidates (/calcom/.yarn/releases/yarn-3.4.1.cjs:435:5145)
docker-calcom-calcom-1  |     at yf.getCandidates (/calcom/.yarn/releases/yarn-3.4.1.cjs:391:1264)
docker-calcom-calcom-1  |     at /calcom/.yarn/releases/yarn-3.4.1.cjs:439:7693
docker-calcom-calcom-1  |     at of (/calcom/.yarn/releases/yarn-3.4.1.cjs:390:11070)
docker-calcom-calcom-1  |     at ge (/calcom/.yarn/releases/yarn-3.4.1.cjs:439:7673)
docker-calcom-calcom-1  |     at async Promise.allSettled (index 19)
docker-calcom-calcom-1  |     at async $s (/calcom/.yarn/releases/yarn-3.4.1.cjs:390:10398)
docker-calcom-calcom-1  |     at async /calcom/.yarn/releases/yarn-3.4.1.cjs:439:8205
docker-calcom-calcom-1  |     at async ti.startProgressPromise (/calcom/.yarn/releases/yarn-3.4.1.cjs:390:47579)
docker-calcom-calcom-1  |     at async je.resolveEverything (/calcom/.yarn/releases/yarn-3.4.1.cjs:439:6233)
docker-calcom-calcom-1 exited with code 1
```

**Comment by InMindVR-Dev** [comment]
same here !

![image](https://user-images.githubusercontent.com/109471520/230765314-0533d18b-5165-49aa-8a32-1fa706e92150.png)

**Comment by TD-INFRANFC** [comment]
if you need urgently calcom as docker container, pull previous image.

In docker-compose.yaml :
`image: calcom.docker.scarf.sh/calcom/cal.com:v2.7.7`

Work fine for me 🙂

**Comment by TD-INFRANFC** [comment]
> 

v2.7.7 or 2.7.6 i'm not sure, I'm not on my workstation

**Comment by marek94901** [comment]
v2.7.7 is ok. I˙m on this version.

**Comment by emrysal** [comment]
I'm unable to reproduce this issue on v2.7.10 - looking at the v2.7.10 & .9 yarn.lock looks right, confirming the v2.7.8 tag has a broken lockfile.

**Comment by InMindVR-Dev** [comment]
> 2.7.7 worked for me thanks to  TD-INFRANFC (image: calcom.docker.scarf.sh/calcom/cal.com:v2.7.7)

**Comment by marek94901** [comment]
Hi, v2.7.13 works well.

**Comment by krumware** [comment]
Thanks for the confirmation!
