### ISSUE TITLE
iCloud Calendar Credentials Not Accepted

### ISSUE THREAD

**Issue by JUNIJC** [calcom/docker#261]
I've created two separate secret app iCloud codes for the Cal icloud calendar sync feature and it fails to login. I checked by copying and pasting the code to ensure there were no spaces before and after, I also manually typed the codes in and tried my regular iCloud password. please view the photos for reference. ![image](https://github.com/calcom/docker/assets/52597087/39e7bed6-b7bb-4ec0-b818-374a33cfd7e3)![image](https://github.com/calcom/docker/assets/52597087/9d68b33f-d987-4ef4-94b9-43f0d7cf6494)

**Comment by wez** [comment]
I'm also seeing this, here are the errors from docker:

```
@calcom/web:start: RangeError: Invalid key length
@calcom/web:start:     at Cipheriv.createCipherBase (node:internal/crypto/cipher:122:19)
@calcom/web:start:     at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:141:3)
@calcom/web:start:     at new Cipheriv (node:internal/crypto/cipher:249:3)
@calcom/web:start:     at Object.createCipheriv (node:crypto:141:10)
@calcom/web:start:     at symmetricEncrypt (/calcom/apps/web/.next/server/chunks/13303.js:29:66)
@calcom/web:start:     at handler (/calcom/apps/web/.next/server/chunks/40625.js:39:95)
@calcom/web:start:     at async handler (/calcom/apps/web/.next/server/pages/api/integrations/[...args].js:645:13) {
@calcom/web:start:   code: 'ERR_CRYPTO_INVALID_KEYLEN'
@calcom/web:start: }
```

**Comment by wez** [comment]
traced it via https://github.com/calcom/docker/issues/183 to not setting the encryption key correctly in the .env file
