### ISSUE TITLE
yarn error when running latest version

### ISSUE THREAD

**Issue by imchairmanm** [calcom/docker#282]
Hello.  On the latest version published to Docker Hub, I'm getting a yarn error similar to the one [described here](https://github.com/calcom/docker/issues/274).  Previous versions of the image work as expected.

The specific output looks like this on the systems I've tested:

```
Internal Error: @calcom/make@workspace:packages/app-store/make: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at P0.getCandidates (/calcom/.yarn/releases/yarn-3.4.1.cjs:435:5145)
    at yf.getCandidates (/calcom/.yarn/releases/yarn-3.4.1.cjs:391:1264)
    at /calcom/.yarn/releases/yarn-3.4.1.cjs:439:7693
    at of (/calcom/.yarn/releases/yarn-3.4.1.cjs:390:11070)
    at ge (/calcom/.yarn/releases/yarn-3.4.1.cjs:439:7673)
    at async Promise.allSettled (index 31)
    at async $s (/calcom/.yarn/releases/yarn-3.4.1.cjs:390:10398)
    at async /calcom/.yarn/releases/yarn-3.4.1.cjs:439:8205
    at async ti.startProgressPromise (/calcom/.yarn/releases/yarn-3.4.1.cjs:390:47579)
    at async je.resolveEverything (/calcom/.yarn/releases/yarn-3.4.1.cjs:439:6233)
```

Do the image need to be rebuilt or is there something I should do on my end?  Thanks!

**Comment by jdreinhardt** [comment]
I had the same issue, but everything worked when I downgraded to the previous release v3.2.7.1. You can use the instructions in #274 but use v3.2.7.1 instead of v3.1.0 and it should work.

**Comment by imchairmanm** [comment]
Thanks for the confirmation.  Yes, I'm using the previous version right now.  Hoping to not have to pin to that version though if possible.

**Comment by aukfood** [comment]
Same problem and downgrade do v3.2.7.1 works

**Comment by imchairmanm** [comment]
The newest image seems to deploy without an issue :+1:

Thanks for the quick fix!

**Comment by aukfood** [comment]
I confirm that works with version 3.2.9
