### ISSUE TITLE
ERR_INVALID_URL after login on domain

### ISSUE THREAD

**Issue by joshhoughton** [calcom/docker#292]
When logging into my Calcom instance, I'm getting this error in my calcom container logs:

```ini
calcom-docker-calcom-1  | @calcom/web:start: 2023-09-26 14:47:51.913 UTC [ERROR] (next-collect/server) - Invalid URL TypeError [ERR_INVALID_URL]: Invalid URL
calcom-docker-calcom-1  | @calcom/web:start:     at new NodeError (node:internal/errors:405:5)
calcom-docker-calcom-1  | @calcom/web:start:     at new URL (node:internal/url:637:13)
calcom-docker-calcom-1  | @calcom/web:start:     at Object.parsePublicUrl (/calcom/node_modules/next-collect/dist/next-shim.js:74:27)
calcom-docker-calcom-1  | @calcom/web:start:     at Object.nextApiHandler (/calcom/node_modules/next-collect/dist/server.js:58:40)
calcom-docker-calcom-1  | @calcom/web:start:     at /calcom/node_modules/next-collect/dist/server.js:180:25
calcom-docker-calcom-1  | @calcom/web:start:     at /calcom/node_modules/next/dist/server/api-utils/node.js:463:16
calcom-docker-calcom-1  | @calcom/web:start:     at /calcom/node_modules/next/dist/server/lib/trace/tracer.js:117:36
calcom-docker-calcom-1  | @calcom/web:start:     at NoopContextManager.with (/calcom/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:25:19)
calcom-docker-calcom-1  | @calcom/web:start:     at ContextAPI.with (/calcom/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
calcom-docker-calcom-1  | @calcom/web:start:     at NoopTracer.startActiveSpan (/calcom/node_modules/@opentelemetry/api/build/src/trace/NoopTracer.js:65:31) {
calcom-docker-calcom-1  | @calcom/web:start:   input: '/api/collect-events',
calcom-docker-calcom-1  | @calcom/web:start:   code: 'ERR_INVALID_URL'
calcom-docker-calcom-1  | @calcom/web:start: }
```

My `.env` file looks like this (I'm not specifying `NEXTAUTH_URL` though this makes no difference seemingly):

```ini
NEXT_PUBLIC_WEBAPP_URL=https://domain.com```

If anyone can point me in the right direction to debug this or if you need any more info.

**Comment by frayos** [comment]
same here

**Comment by malua** [comment]
Did you ever solve this?
