### ISSUE TITLE
No database tables found with default setup

### ISSUE THREAD

**Issue by notflip** [calcom/docker#295]
I'm following the docker setup from this README, I'm always getting errors like these

```
calcom-docker-calcom-1  | Invalid `prisma.app.findFirst()` invocation:
calcom-docker-calcom-1  |
calcom-docker-calcom-1  |
calcom-docker-calcom-1  | The table `public.App` does not exist in the current database.
calcom-docker-calcom-1  |     at vn.handleRequestError (/calcom/node_modules/@prisma/client/runtime/library.js:123:6730)
calcom-docker-calcom-1  |     at vn.handleAndLogRequestError (/calcom/node_modules/@prisma/client/runtime/library.js:123:6119)
calcom-docker-calcom-1  |     at vn.request (/calcom/node_modules/@prisma/client/runtime/library.js:123:5839)
calcom-docker-calcom-1  |     at async l (/calcom/node_modules/@prisma/client/runtime/library.js:128:9763)
calcom-docker-calcom-1  |     at async createApp (/calcom/packages/prisma/seed-app-store.ts:169:22)
calcom-docker-calcom-1  |     at async main (/calcom/packages/prisma/seed-app-store.ts:373:5) {
calcom-docker-calcom-1  |   code: 'P2021',
calcom-docker-calcom-1  |   clientVersion: '5.2.0',
calcom-docker-calcom-1  |   meta: { table: 'public.App' }
calcom-docker-calcom-1  | }
calcom-docker-calcom-1  | Could not upsert app: zoho-bigin. Error: PrismaClientKnownRequestError:
calcom-docker-calcom-1  | Invalid `prisma.app.findFirst()` invocation:
calcom-docker-calcom-1  |
calcom-docker-calcom-1  |
calcom-docker-calcom-1  | The table `public.App` does not exist in the current database.
calcom-docker-calcom-1  |     at vn.handleRequestError (/calcom/node_modules/@prisma/client/runtime/library.js:123:6730)
calcom-docker-calcom-1  |     at vn.handleAndLogRequestError (/calcom/node_modules/@prisma/client/runtime/library.js:123:6119)
calcom-docker-calcom-1  |     at vn.request (/calcom/node_modules/@prisma/client/runtime/library.js:123:5839)
calcom-docker-calcom-1  |     at async l (/calcom/node_modules/@prisma/client/runtime/library.js:128:9763)
calcom-docker-calcom-1  |     at async createApp (/calcom/packages/prisma/seed-app-store.ts:169:22)
calcom-docker-calcom-1  |     at async main (/calcom/packages/prisma/seed-app-store.ts:373:5) {
calcom-docker-calcom-1  |   code: 'P2021',
calcom-docker-calcom-1  |   clientVersion: '5.2.0',
calcom-docker-calcom-1  |   meta: { table: 'public.App' }
calcom-docker-calcom-1  | }
calcom-docker-calcom-1  | Could not upsert app: zohocrm. Error: PrismaClientKnownRequestError:
calcom-docker-calcom-1  | Invalid `prisma.app.findFirst()` invocation:
calcom-docker-calcom-1  |
calcom-docker-calcom-1  |
calcom-docker-calcom-1  | The table `public.App` does not exist in the current database.
calcom-docker-calcom-1  |     at vn.handleRequestError (/calcom/node_modules/@prisma/client/runtime/library.js:123:6730)
calcom-docker-calcom-1  |     at vn.handleAndLogRequestError (/calcom/node_modules/@prisma/client/runtime/library.js:123:6119)
calcom-docker-calcom-1  |     at vn.request (/calcom/node_modules/@prisma/client/runtime/library.js:123:5839)
calcom-docker-calcom-1  |     at async l (/calcom/node_modules/@prisma/client/runtime/library.js:128:9763)
calcom-docker-calcom-1  |     at async createApp (/calcom/packages/prisma/seed-app-store.ts:169:22)
calcom-docker-calcom-1  |     at async main (/calcom/packages/prisma/seed-app-store.ts:373:5) {
calcom-docker-calcom-1  |   code: 'P2021',
calcom-docker-calcom-1  |   clientVersion: '5.2.0',
calcom-docker-calcom-1  |   meta: { table: 'public.App' }
calcom-docker-calcom-1  | }
calcom-docker-calcom-1  | Could not upsert app: zoom. Error: PrismaClientKnownRequestError:
calcom-docker-calcom-1  | Invalid `prisma.app.findFirst()` invocation:
calcom-docker-calcom-1  |
calcom-docker-calcom-1  |
calcom-docker-calcom-1  | The table `public.App` does not exist in the current database.
calcom-docker-calcom-1  |     at vn.handleRequestError (/calcom/node_modules/@prisma/client/runtime/library.js:123:6730)
calcom-docker-calcom-1  |     at vn.handleAndLogRequestError (/calcom/node_modules/@prisma/client/runtime/library.js:123:6119)
calcom-docker-calcom-1  |     at vn.request (/calcom/node_modules/@prisma/client/runtime/library.js:123:5839)
calcom-docker-calcom-1  |     at async l (/calcom/node_modules/@prisma/client/runtime/library.js:128:9763)
calcom-docker-calcom-1  |     at async createApp (/calcom/packages/prisma/seed-app-store.ts:169:22)
calcom-docker-calcom-1  |     at async main (/calcom/packages/prisma/seed-app-store.ts:373:5) {
calcom-docker-calcom-1  |   code: 'P2021',
calcom-docker-calcom-1  |   clientVersion: '5.2.0',
calcom-docker-calcom-1  |   meta: { table: 'public.App' }
calcom-docker-calcom-1  | }
calcom-docker-calcom-1  | PrismaClientKnownRequestError:
calcom-docker-calcom-1  | Invalid `prisma.app_RoutingForms_Form.findUnique()` invocation:
```

**Comment by tigerblue77** [comment]
Yes, it's badly packaged. The container should be able to detect empty PostgreSQL database container and run some initialization SQL script

**Comment by tigerblue77** [comment]
Yes, it's badly packaged. The container should be able to detect empty PostgreSQL database container and run some initialization SQL script.

As a workaround, you can run every .sql script contained here : https://github.com/calcom/cal.com/tree/6eadadec736e5d8f4f686959496447fd33607a2b/packages/prisma/migrations

**Comment by tigerblue77** [comment]
Yes, it's badly packaged. The container should be able to detect empty PostgreSQL database container and run some initialization SQL script.

As a workaround, you can run every .sql script contained here : https://github.com/calcom/cal.com/tree/main/packages/prisma/migrations

**Comment by Chinoman10** [comment]
> Yes, it's badly packaged. The container should be able to detect empty PostgreSQL database container and run some initialization SQL script.
> 
> As a workaround, you can run every .sql script contained here : https://github.com/calcom/cal.com/tree/main/packages/prisma/migrations

Who can fix the package?

**Comment by tigerblue77** [comment]
Hello @zomars @PeerRich @emrysal,
sorry to ping you, as you're the main contributors to this repository, could you please have a look to this issue please ? 😉
Thanks for all the amazing work you do ! 🚀
