### ISSUE TITLE
Internal Error: @calcom/mock-payment-app: This package doesn't seem to be present in your lockfile

### ISSUE THREAD

**Issue by davidknezic** [calcom/docker#320]
Looks similar to #234, but happens during `docker run` and not the build step.

`docker build` based off tag [v3.7.0](https://github.com/calcom/docker/tree/v3.7.0) with the `calcom` submodule up-to-date works great.

However, the `docker run` fails:

```sh
docker run --rm -e DATABASE_URL=postgres://postgres:password@host.docker.internal:5432/calcom -e NEXTAUTH_SECRET=secret -e CALENDSO_ENCRYPTION_KEY=[REDACTED] -e NEXT_PUBLIC_WEBAPP_URL=http://localhost:3000 -p 3000:3000 -it my/calcom:v3.7.0
+ scripts/replace-placeholder.sh https://my.calcom http://localhost:3000
Replacing all statically built instances of https://my.calcom with http://localhost:3000.
+ scripts/wait-for-it.sh -- echo database is up
Error: you need to provide a host and port to test.
Usage:
  scripts/wait-for-it.sh host:port|url [-t timeout] [-- command args]
  -q | --quiet                        Do not output any status messages
  -t TIMEOUT | --timeout=timeout      Timeout in seconds, zero for no timeout
  -- COMMAND ARGS                     Execute command with args after the test finishes
+ npx prisma migrate deploy --schema /calcom/packages/prisma/schema.prisma
Prisma schema loaded from packages/prisma/schema.prisma
Datasource "db": PostgreSQL database "calcom4", schema "public" at "host.docker.internal:5432"

234 migrations found in prisma/migrations


No pending migrations to apply.
npm notice 
npm notice New minor version of npm available! 10.2.3 -> 10.3.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.3.0
npm notice Run npm install -g npm@10.3.0 to update!
npm notice 
+ npx ts-node --transpile-only /calcom/packages/prisma/seed-app-store.ts
📲 Updated app: 'apple-calendar'
📲 Updated app: 'caldav-calendar'
Error adding google credentials to DB: Unexpected end of JSON input
📲 Updated app: 'jitsi'
📲 Updated app: [LOTS OF DIFFERENT APPS]
📲 Updated app: 'zoom'
Skipping Routing Form - Seeding - Pro User not found
+ yarn start
Internal Error: @calcom/mock-payment-app@workspace:packages/app-store/mock-payment-app: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at P0.getCandidates (/calcom/.yarn/releases/yarn-3.4.1.cjs:435:5145)
    at yf.getCandidates (/calcom/.yarn/releases/yarn-3.4.1.cjs:391:1264)
    at /calcom/.yarn/releases/yarn-3.4.1.cjs:439:7693
    at of (/calcom/.yarn/releases/yarn-3.4.1.cjs:390:11070)
    at ge (/calcom/.yarn/releases/yarn-3.4.1.cjs:439:7673)
    at async Promise.allSettled (index 38)
    at async $s (/calcom/.yarn/releases/yarn-3.4.1.cjs:390:10398)
    at async /calcom/.yarn/releases/yarn-3.4.1.cjs:439:8205
    at async ti.startProgressPromise (/calcom/.yarn/releases/yarn-3.4.1.cjs:390:47579)
    at async je.resolveEverything (/calcom/.yarn/releases/yarn-3.4.1.cjs:439:6233)
```

**Comment by davidknezic** [comment]
Thank you @zomars will try again with the updated `calcom` submodule: https://github.com/calcom/cal.com/commit/7b8902a769f9adb93a5909d3015730268d400ca8

**Comment by davidknezic** [comment]
It's resolved ✨
