### ISSUE TITLE
Error on first user signup - JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by shibacomputer** [calcom/docker#324]
I'm trying to deploy the docker project on a personal server running Fedora Server 39 and Docker. Using basically default settings in my `.env`, and updating only `NEXT_PUBLIC_WEBAPP_URL, NEXTAUTH_SECRET`, `CALENDSO_ENCRYPTION_KEY` and `POSTGRES_PASSWORD`, I am getting this error when inviting my first user:

![image](https://github.com/calcom/docker/assets/737950/b2968beb-3b90-46c5-a65e-c8fd0c156128)

```
calcom-1  | @calcom/web:start: Error: @vercel/edge-config: No connection string provided
calcom-1  | @calcom/web:start:     at m (file:///calcom/apps/web/.next/server/middleware.js:90:19)
calcom-1  | @calcom/web:start:     at E (file:///calcom/apps/web/.next/server/middleware.js:160:15)
calcom-1  | @calcom/web:start:     at N (file:///calcom/apps/web/.next/server/middleware.js:162:18)
calcom-1  | @calcom/web:start:     at middleware (file:///calcom/apps/web/.next/server/middleware.js:835:40)
calcom-1  | @calcom/web:start:     at Object.middleware (file:///calcom/apps/web/.next/server/middleware.js:750:32)
calcom-1  | @calcom/web:start:     at Object.handler (file:///calcom/apps/web/.next/server/middleware.js:2696:55)
calcom-1  | @calcom/web:start:     at <unknown> (file:///calcom/apps/web/.next/server/middleware.js:4420:23)
calcom-1  | @calcom/web:start:     at AsyncLocalStorage.run (node:async_hooks:338:14)
calcom-1  | @calcom/web:start:     at Object.wrap (file:///calcom/apps/web/.next/server/middleware.js:4251:24)
calcom-1  | @calcom/web:start:     at adapter (file:///calcom/apps/web/.next/server/middleware.js:4407:53)
calcom-1  | @calcom/web:start: react-i18next:: You will need to pass in an i18next instance by using initReactI18next
calcom-1  | @calcom/web:start: 
calcom-1  | @calcom/web:start:  ⚠ metadata.metadataBase is not set for resolving social open graph or twitter images, using "http://localhost:3000". See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase
calcom-1  | @calcom/web:start: react-i18next:: You will need to pass in an i18next instance by using initReactI18next
calcom-1  | @calcom/web:start: 12:17:51:411    WARNorgDomains.ts Match of WEBAPP_URL with ALLOWED_HOSTNAME failed {
calcom-1  | @calcom/web:start:   WEBAPP_URL: 'https://mydomain.com',
calcom-1  | @calcom/web:start:   ALLOWED_HOSTNAMES: []
calcom-1  | @calcom/web:start: }
```

Adding `ALLOWED_HOSTNAMES` does not make a difference.

I also posted this on the Docker channel in Discord but given the presence of crypto and developer scam/spam bots it's very clear that the Discord community is unmoderated.

**Comment by tomcatcw1980** [comment]
similar to #326

**Comment by gcarrarom** [comment]
Any news? Did someone find out what is happening here? I'm running into the same issue here.
