### ISSUE TITLE
Invalid key length on CALENDSO_ENCRYPTION KEY

### ISSUE THREAD

**Issue by ozzyoss77** [calcom/docker#333]
Hello everyone, I have a deployment of cal.com with the following characteristics:

- AWS EC2 instance with 2VCPU and 2GB RAM, Ubuntu 22.04 LTS.
- Docker Compose deployment.

Everything works fine, but when trying to activate 2FA, it tells me that something went wrong. Checking the Docker Compose logs, I have this message in the console:

`RangeError: Invalid key length
calcom-1  | @calcom/web:start:     at Cipheriv.createCipherBase (node:internal/crypto/cipher:122:19)
calcom-1  | @calcom/web:start:     at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:141:3)
calcom-1  | @calcom/web:start:     at new Cipheriv (node:internal/crypto/cipher:249:3)
calcom-1  | @calcom/web:start:     at Object.createCipheriv (node:crypto:141:10)
calcom-1  | @calcom/web:start:     at symmetricEncrypt (/calcom/apps/web/.next/server/chunks/69559.js:1:278)
calcom-1  | @calcom/web:start:     at handler (/calcom/apps/web/.next/server/pages/api/auth/two-factor/totp/setup.js:1:3027) {
calcom-1  | @calcom/web:start:   code: 'ERR_CRYPTO_INVALID_KEYLEN'
calcom-1  | @calcom/web:start: }
calcom-1  | @calcom/web:start: RangeError: Invalid key length
calcom-1  | @calcom/web:start:     at Cipheriv.createCipherBase (node:internal/crypto/cipher:122:19)
calcom-1  | @calcom/web:start:     at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:141:3)
calcom-1  | @calcom/web:start:     at new Cipheriv (node:internal/crypto/cipher:249:3)
calcom-1  | @calcom/web:start:     at Object.createCipheriv (node:crypto:141:10)
calcom-1  | @calcom/web:start:     at symmetricEncrypt (/calcom/apps/web/.next/server/chunks/69559.js:1:278)
calcom-1  | @calcom/web:start:     at handler (/calcom/apps/web/.next/server/pages/api/auth/two-factor/totp/setup.js:1:3027) {
calcom-1  | @calcom/web:start:   code: 'ERR_CRYPTO_INVALID_KEYLEN'
calcom-1  | @calcom/web:start: }`

From what I understand, there is an issue with the length of the secret used to encrypt the information. Can someone help me with the necessary specifications to get this accepted?

I'm already using `openssl rand -base64 32` to generate a random string, but I still can't get it to work.

Thanks in advance.

**Comment by johan-cruxdata** [comment]
have you tried the old guidance of `openssl rand -base64 24`?

**Comment by tiagocdr** [comment]
Having the exact same problem

**Comment by ozzyoss77** [comment]
> have you tried the old guidance of `openssl rand -base64 24`?

Yes, that it works, Thanks

**Comment by Stefan2706** [comment]
Hi,

ich habe das gleiche Thema. Was muss ich genau machen? Kann mir jemand helfen?

Vielen Dank

Viele Grüße
Stefan

**Comment by krumware** [comment]
## Solution Confirmed ✅

As confirmed by @ozzyoss77 and @Novapixel1010, the solution is to use a 24-character encryption key:

```bash
openssl rand -base64 24
```

### Why 24 characters?
The application requires at least 24 characters for the `CALENDSO_ENCRYPTION_KEY` to properly encrypt 2FA data. The default `secret` (6 characters) in `.env.example` is insufficient.

### Complete Setup:
1. Generate encryption key: `openssl rand -base64 24`
2. Generate auth secret: `openssl rand -base64 32`
3. Update your `.env` file with these values
4. Restart your containers

### Status:
- ✅ Root cause identified: insufficient key length
- ✅ Solution verified by multiple users
- ✅ Works with current version (v5.4.17 confirmed)

This issue should be resolved with proper documentation updates to prevent future occurrences.
