### ISSUE TITLE
cal.com Docker container keeps restarting: "autocheckin: This package doesn't seem to be present in your lockfile"

### ISSUE THREAD

**Issue by chriscroome** [calcom/docker#353]
I've followed the [Build and Run Cal.com instructions](https://github.com/calcom/docker?tab=readme-ov-file#advanced-users-build-and-run-calcom) and I'm using the [latest version](https://github.com/calcom/docker/releases/tag/v4.0.4) and also I also included the [changes suggested on issue 343](https://github.com/calcom/docker/issues/343#issuecomment-2051871827) and `docker compose build calcom` completes but the container keeps restarting, I have Docker logging to `/var/log/syslog` and that contains:

```
2024-04-26T13:01:33.602349+00:00 cal df6748830895[3085]: + scripts/wait-for-it.sh database:5432 -- echo database is up
2024-04-26T13:01:33.616448+00:00 cal df6748830895[3085]: nc command is missing!
2024-04-26T13:01:33.617578+00:00 cal df6748830895[3085]: + npx prisma migrate deploy --schema /calcom/packages/prisma/schema.prisma
2024-04-26T13:01:35.023768+00:00 cal df6748830895[3085]: Prisma schema loaded from packages/prisma/schema.prisma
2024-04-26T13:01:35.060681+00:00 cal df6748830895[3085]: Datasource "db": PostgreSQL database "cal", schema "public" at "database:5432"
2024-04-26T13:01:35.239505+00:00 cal df6748830895[3085]: 283 migrations found in prisma/migrations
2024-04-26T13:01:35.310301+00:00 cal df6748830895[3085]: No pending migrations to apply.
2024-04-26T13:01:35.533245+00:00 cal df6748830895[3085]: + npx ts-node --transpile-only /calcom/packages/prisma/seed-app-store.ts
2024-04-26T13:01:37.651448+00:00 cal df6748830895[3085]: 📲 Updated app: 'apple-calendar'
2024-04-26T13:01:37.658262+00:00 cal df6748830895[3085]: 📲 Updated app: 'caldav-calendar'
2024-04-26T13:01:37.664829+00:00 cal df6748830895[3085]: 📲 Updated app: 'google-calendar'
2024-04-26T13:01:37.670992+00:00 cal df6748830895[3085]: 📲 Updated app: 'google-meet'
2024-04-26T13:01:37.676259+00:00 cal df6748830895[3085]: 📲 Updated app: 'jitsi'
2024-04-26T13:01:37.681535+00:00 cal df6748830895[3085]: 📲 Updated app: 'wipe-my-cal'
2024-04-26T13:01:37.686267+00:00 cal df6748830895[3085]: 📲 Updated app: 'make'
2024-04-26T13:01:37.690788+00:00 cal df6748830895[3085]: 📲 Updated app: 'huddle01'
2024-04-26T13:01:37.695940+00:00 cal df6748830895[3085]: 📲 Updated app: 'alby'
2024-04-26T13:01:37.700775+00:00 cal df6748830895[3085]: 📲 Updated app: 'amie'
2024-04-26T13:01:37.705674+00:00 cal df6748830895[3085]: 📲 Updated app: 'apple-calendar'
2024-04-26T13:01:37.710354+00:00 cal df6748830895[3085]: 📲 Updated app: 'around'
2024-04-26T13:01:37.717168+00:00 cal df6748830895[3085]: 📲 Updated app: 'autocheckin'
2024-04-26T13:01:37.731248+00:00 cal df6748830895[3085]: 📲 Updated app: 'basecamp3'
2024-04-26T13:01:37.736232+00:00 cal df6748830895[3085]: 📲 Updated app: 'cal-ai'
2024-04-26T13:01:37.741016+00:00 cal df6748830895[3085]: 📲 Updated app: 'caldav-calendar'
2024-04-26T13:01:37.745436+00:00 cal df6748830895[3085]: 📲 Updated app: 'campfire'
2024-04-26T13:01:37.750200+00:00 cal df6748830895[3085]: 📲 Updated app: 'closecom'
2024-04-26T13:01:37.755148+00:00 cal df6748830895[3085]: 📲 Updated app: 'cron'
2024-04-26T13:01:37.760403+00:00 cal df6748830895[3085]: 📲 Updated app: 'daily-video'
2024-04-26T13:01:37.766108+00:00 cal df6748830895[3085]: 📲 Updated app: 'deel'
2024-04-26T13:01:37.771066+00:00 cal df6748830895[3085]: 📲 Updated app: 'demodesk'
2024-04-26T13:01:37.776147+00:00 cal df6748830895[3085]: 📲 Updated app: 'discord'
2024-04-26T13:01:37.791699+00:00 cal df6748830895[3085]: 📲 Updated app: 'eightxeight'
2024-04-26T13:01:37.801677+00:00 cal df6748830895[3085]: 📲 Updated app: 'element-call'
2024-04-26T13:01:37.809691+00:00 cal df6748830895[3085]: 📲 Updated app: 'exchange2013-calendar'
2024-04-26T13:01:37.818671+00:00 cal df6748830895[3085]: 📲 Updated app: 'exchange2016-calendar'
2024-04-26T13:01:37.828855+00:00 cal df6748830895[3085]: 📲 Updated app: 'exchange'
2024-04-26T13:01:37.839485+00:00 cal df6748830895[3085]: 📲 Updated app: 'facetime'
2024-04-26T13:01:37.845535+00:00 cal df6748830895[3085]: 📲 Updated app: 'fathom'
2024-04-26T13:01:37.850912+00:00 cal df6748830895[3085]: 📲 Updated app: 'feishu-calendar'
2024-04-26T13:01:37.865761+00:00 cal df6748830895[3085]: 📲 Updated app: 'ga4'
2024-04-26T13:01:37.877663+00:00 cal df6748830895[3085]: 📲 Updated app: 'giphy'
2024-04-26T13:01:37.887830+00:00 cal df6748830895[3085]: 📲 Updated app: 'google-calendar'
2024-04-26T13:01:37.902315+00:00 cal df6748830895[3085]: 📲 Updated app: 'google-meet'
2024-04-26T13:01:37.913142+00:00 cal df6748830895[3085]: 📲 Updated app: 'gtm'
2024-04-26T13:01:37.924244+00:00 cal df6748830895[3085]: 📲 Updated app: 'hubspot'
2024-04-26T13:01:37.942486+00:00 cal df6748830895[3085]: 📲 Updated app: 'huddle01'
2024-04-26T13:01:37.952848+00:00 cal df6748830895[3085]: 📲 Updated app: 'ics-feed'
2024-04-26T13:01:37.987671+00:00 cal df6748830895[3085]: 📲 Updated app: 'intercom'
2024-04-26T13:01:37.995325+00:00 cal df6748830895[3085]: 📲 Updated app: 'jelly'
2024-04-26T13:01:38.006003+00:00 cal df6748830895[3085]: 📲 Updated app: 'jitsi'
2024-04-26T13:01:38.019401+00:00 cal df6748830895[3085]: 📲 Updated app: 'lark-calendar'
2024-04-26T13:01:38.025217+00:00 cal df6748830895[3085]: 📲 Updated app: 'linear'
2024-04-26T13:01:38.033183+00:00 cal df6748830895[3085]: 📲 Updated app: 'make'
2024-04-26T13:01:38.038875+00:00 cal df6748830895[3085]: 📲 Updated app: 'matomo'
2024-04-26T13:01:38.045556+00:00 cal df6748830895[3085]: 📲 Updated app: 'metapixel'
2024-04-26T13:01:38.051374+00:00 cal df6748830895[3085]: 📲 Updated app: 'mirotalk'
2024-04-26T13:01:38.056460+00:00 cal df6748830895[3085]: 📲 Updated app: 'mock-payment-app'
2024-04-26T13:01:38.063871+00:00 cal df6748830895[3085]: 📲 Updated app: 'n8n'
2024-04-26T13:01:38.075307+00:00 cal df6748830895[3085]: 📲 Updated app: 'office365-calendar'
2024-04-26T13:01:38.085288+00:00 cal df6748830895[3085]: 📲 Updated app: 'msteams'
2024-04-26T13:01:38.094226+00:00 cal df6748830895[3085]: 📲 Updated app: 'paypal'
2024-04-26T13:01:38.099267+00:00 cal df6748830895[3085]: 📲 Updated app: 'ping'
2024-04-26T13:01:38.104244+00:00 cal df6748830895[3085]: 📲 Updated app: 'pipedream'
2024-04-26T13:01:38.109583+00:00 cal df6748830895[3085]: 📲 Updated app: 'pipedrive-crm'
2024-04-26T13:01:38.114825+00:00 cal df6748830895[3085]: 📲 Updated app: 'plausible'
2024-04-26T13:01:38.120222+00:00 cal df6748830895[3085]: 📲 Updated app: 'qr_code'
2024-04-26T13:01:38.139934+00:00 cal df6748830895[3085]: 📲 Updated app: 'raycast'
2024-04-26T13:01:38.150103+00:00 cal df6748830895[3085]: 📲 Updated app: 'riverside'
2024-04-26T13:01:38.160275+00:00 cal df6748830895[3085]: 📲 Updated app: 'roam'
2024-04-26T13:01:38.170253+00:00 cal df6748830895[3085]: 📲 Updated app: 'routing-forms'
2024-04-26T13:01:38.176613+00:00 cal df6748830895[3085]: 📲 Updated app: 'salesforce'
2024-04-26T13:01:38.183899+00:00 cal df6748830895[3085]: 📲 Updated app: 'salesroom'
2024-04-26T13:01:38.189578+00:00 cal df6748830895[3085]: 📲 Updated app: 'sendgrid'
2024-04-26T13:01:38.204561+00:00 cal df6748830895[3085]: 📲 Updated app: 'shimmervideo'
2024-04-26T13:01:38.210062+00:00 cal df6748830895[3085]: 📲 Updated app: 'signal'
2024-04-26T13:01:38.219316+00:00 cal df6748830895[3085]: 📲 Updated app: 'sirius_video'
2024-04-26T13:01:38.231270+00:00 cal df6748830895[3085]: 📲 Updated app: 'stripe'
2024-04-26T13:01:38.242121+00:00 cal df6748830895[3085]: 📲 Updated app: 'sylapsvideo'
2024-04-26T13:01:38.252933+00:00 cal df6748830895[3085]: 📲 Updated app: 'tandem'
2024-04-26T13:01:38.258459+00:00 cal df6748830895[3085]: 📲 Updated app: 'telegram'
2024-04-26T13:01:38.263809+00:00 cal df6748830895[3085]: 📲 Updated app: 'typeform'
2024-04-26T13:01:38.268844+00:00 cal df6748830895[3085]: 📲 Updated app: 'vimcal'
2024-04-26T13:01:38.273986+00:00 cal df6748830895[3085]: 📲 Updated app: 'vital-automation'
2024-04-26T13:01:38.279283+00:00 cal df6748830895[3085]: 📲 Updated app: 'weather_in_your_calendar'
2024-04-26T13:01:38.285426+00:00 cal df6748830895[3085]: 📲 Updated app: 'webex'
2024-04-26T13:01:38.290907+00:00 cal df6748830895[3085]: 📲 Updated app: 'whatsapp'
2024-04-26T13:01:38.296688+00:00 cal df6748830895[3085]: 📲 Updated app: 'whereby'
2024-04-26T13:01:38.304639+00:00 cal df6748830895[3085]: 📲 Updated app: 'wipe-my-cal'
2024-04-26T13:01:38.310896+00:00 cal df6748830895[3085]: 📲 Updated app: 'wordpress'
2024-04-26T13:01:38.316366+00:00 cal df6748830895[3085]: 📲 Updated app: 'zapier'
2024-04-26T13:01:38.321413+00:00 cal df6748830895[3085]: 📲 Updated app: 'zoho-bigin'
2024-04-26T13:01:38.328639+00:00 cal df6748830895[3085]: 📲 Updated app: 'zohocalendar'
2024-04-26T13:01:38.335901+00:00 cal df6748830895[3085]: 📲 Updated app: 'zohocrm'
2024-04-26T13:01:38.341217+00:00 cal df6748830895[3085]: 📲 Updated app: 'zoom'
2024-04-26T13:01:38.347634+00:00 cal df6748830895[3085]: Skipping Routing Form - Seeding - Pro User not found
2024-04-26T13:01:38.469207+00:00 cal df6748830895[3085]: + yarn start
2024-04-26T13:01:40.823076+00:00 cal df6748830895[3085]: Internal Error: @calcom/autocheckin@workspace:packages/app-store/autocheckin: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
2024-04-26T13:01:40.823239+00:00 cal df6748830895[3085]:     at P0.getCandidates (/calcom/.yarn/releases/yarn-3.4.1.cjs:435:5145)
2024-04-26T13:01:40.823316+00:00 cal df6748830895[3085]:     at yf.getCandidates (/calcom/.yarn/releases/yarn-3.4.1.cjs:391:1264)
2024-04-26T13:01:40.823389+00:00 cal df6748830895[3085]:     at /calcom/.yarn/releases/yarn-3.4.1.cjs:439:7693
2024-04-26T13:01:40.823460+00:00 cal df6748830895[3085]:     at of (/calcom/.yarn/releases/yarn-3.4.1.cjs:390:11070)
2024-04-26T13:01:40.823532+00:00 cal df6748830895[3085]:     at ge (/calcom/.yarn/releases/yarn-3.4.1.cjs:439:7673)
2024-04-26T13:01:40.823614+00:00 cal df6748830895[3085]:     at async Promise.allSettled (index 8)
2024-04-26T13:01:40.823676+00:00 cal df6748830895[3085]:     at async $s (/calcom/.yarn/releases/yarn-3.4.1.cjs:390:10398)
2024-04-26T13:01:40.823738+00:00 cal df6748830895[3085]:     at async /calcom/.yarn/releases/yarn-3.4.1.cjs:439:8205
2024-04-26T13:01:40.823818+00:00 cal df6748830895[3085]:     at async ti.startProgressPromise (/calcom/.yarn/releases/yarn-3.4.1.cjs:390:47579)
2024-04-26T13:01:40.823889+00:00 cal df6748830895[3085]:     at async je.resolveEverything (/calcom/.yarn/releases/yarn-3.4.1.cjs:439:6233)
2024-04-26T13:01:41.086268+00:00 cal systemd[1]: docker-df6748830895077c01f095556cefe47d801110d7096684924efbdadf8dace813.scope: Deactivated successfully.
2024-04-26T13:01:41.086483+00:00 cal systemd[1]: docker-df6748830895077c01f095556cefe47d801110d7096684924efbdadf8dace813.scope: Consumed 7.037s CPU time.
2024-04-26T13:01:41.111167+00:00 cal dockerd[3085]: time="2024-04-26T13:01:41.111014581Z" level=info msg="ignoring event" container=df6748830895077c01f095556cefe47d801110d7096684924efbdadf8dace813 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
2024-04-26T13:01:41.112262+00:00 cal containerd[533]: time="2024-04-26T13:01:41.111930757Z" level=info msg="shim disconnected" id=df6748830895077c01f095556cefe47d801110d7096684924efbdadf8dace813
2024-04-26T13:01:41.112528+00:00 cal containerd[533]: time="2024-04-26T13:01:41.112477153Z" level=warning msg="cleaning up after shim disconnected" id=df6748830895077c01f095556cefe47d801110d7096684924efbdadf8dace813 namespace=moby
```

Does anyone have a suggestion for fixing this?

**Comment by chriscroome** [comment]
Is this merged pull request related to this issue?

https://github.com/calcom/cal.com/pull/14683

**Comment by chriscroome** [comment]
The Yarn lock file has been updated for autocheckin in this merge request https://github.com/calcom/cal.com/pull/14812 so now it all works :partying_face:
