### ISSUE TITLE
Error:  {"name":"PrismaClientKnownRequestError","code":"P2022","clientVersion":"5.4.2","meta":{"column":"isPlatformManaged"}}

### ISSUE THREAD

**Issue by ronenlazowski** [calcom/docker#406]
I can't get past the first step of setup with cal.com. Here are my logs.

```text  error  warn  system  array  login  

PrismaClientKnownRequestError: 
Invalid `prisma.user.findFirst()` invocation:


The column `users.lastActiveAt` does not exist in the current database.
    at Cn.handleRequestError (/calcom/node_modules/@prisma/client/runtime/library.js:123:6817)
    at Cn.handleAndLogRequestError (/calcom/node_modules/@prisma/client/runtime/library.js:123:6206)
    at Cn.request (/calcom/node_modules/@prisma/client/runtime/library.js:123:5926)
    at async l (/calcom/node_modules/@prisma/client/runtime/library.js:128:9968)
    at async seedAppData (/calcom/packages/prisma/seed-app-store.ts:31:19)
    at async main (/calcom/packages/prisma/seed-app-store.ts:407:3) {
  code: 'P2022',
  clientVersion: '5.4.2',
  meta: { column: 'users.lastActiveAt' }
}
+ yarn start
📲 Created app: 'paypal'
📲 Created app: 'ping'
📲 Created app: 'pipedream'
📲 Created app: 'pipedrive-crm'
📲 Created app: 'plausible'
📲 Created app: 'posthog'
📲 Created app: 'qr_code'
📲 Created app: 'raycast'
📲 Created app: 'retell-ai'
📲 Created app: 'riverside'
📲 Created app: 'roam'
📲 Created app: 'routing-forms'
📲 Created app: 'salesforce'
📲 Created app: 'salesroom'
📲 Created app: 'sendgrid'
📲 Created app: 'shimmervideo'
📲 Created app: 'signal'
📲 Created app: 'sirius_video'
📲 Created app: 'skype'
📲 Created app: 'stripe'
📲 Created app: 'sylapsvideo'
📲 Created app: 'synthflow'
📲 Created app: 'tandem'
📲 Created app: 'telegram'
📲 Created app: 'telli'
📲 Created app: 'twipla'
📲 Created app: 'typeform'
📲 Created app: 'umami'
📲 Created app: 'vimcal'
📲 Created app: 'vital-automation'
📲 Created app: 'weather_in_your_calendar'
📲 Created app: 'webex'
📲 Created app: 'whatsapp'
📲 Created app: 'whereby'
📲 Updated app: 'wipe-my-cal'
📲 Created app: 'wordpress'
📲 Created app: 'zapier'
📲 Created app: 'zoho-bigin'
📲 Created app: 'zohocalendar'
📲 Created app: 'zohocrm'
📲 Created app: 'zoom'
• Packages in scope: @calcom/web
• Running start in 1 packages
• Remote caching disabled
@calcom/web:start: cache bypass, force executing b2695a7cdc2905b2
@calcom/web:start: Duplicate value found in common.json keys:   emailed_host_and_attendee and emailed_you_and_attendees
@calcom/web:start: Duplicate value found in common.json keys:   emailed_host_and_attendee_recurring and emailed_you_and_attendees_recurring
@calcom/web:start: Duplicate value found in common.json keys:   seats_available_other and seats_available_one
@calcom/web:start: Duplicate value found in common.json keys:   event_payments_tab_title and payments
@calcom/web:start: Duplicate value found in common.json keys:   location_variable and location
@calcom/web:start: Duplicate value found in common.json keys:   additional_notes_variable and additional_notes
@calcom/web:start: Duplicate value found in common.json keys:   weekly and bookerlayout_week_view
@calcom/web:start: Duplicate value found in common.json keys:   already_have_account and already_have_an_account
@calcom/web:start: Duplicate value found in common.json keys:   timezone_variable and timezone
@calcom/web:start: Duplicate value found in common.json keys:   scheduling_for_your_team and workflow_automation
@calcom/web:start: Duplicate value found in common.json keys:   oauth_form_title and oAuth_client_creation_form
@calcom/web:start: Duplicate value found in common.json keys:   oauth_form_description and oAuth_client_creation_form_description
@calcom/web:start: Duplicate value found in common.json keys:   saml_sso and saml_config
@calcom/web:start: Duplicate value found in common.json keys:   advanced_managed_events_description and unified_billing_description
@calcom/web:start: Duplicate value found in common.json keys:   org_admin_no_slots|heading and org_admin_no_slots|subject
@calcom/web:start: Duplicate value found in common.json keys:   email_team_invite|subject|invited_to_subteam and user_invited_you_to_subteam
@calcom/web:start: Duplicate value found in common.json keys:   email_team_invite|heading|invited_to_regular_team and email_no_user_invite_heading_team
@calcom/web:start: Duplicate value found in common.json keys:   email_team_invite|content|invited_to_regular_team and email_user_invite_subheading_team
@calcom/web:start: Duplicate value found in common.json keys:   create_an_out_of_office and ooo_create_entry_modal
@calcom/web:start: Duplicate value found in common.json keys:   attendee_timezone_info and attendee_timezone_variable
@calcom/web:start: Duplicate value found in common.json keys:   event_start_time_in_attendee_timezone_info and event_start_time_in_attendee_timezone_variable
@calcom/web:start: Duplicate value found in common.json keys:   event_end_time_in_attendee_timezone_info and event_end_time_in_attendee_timezone_variable
@calcom/web:start:   ▲ Next.js 13.5.7
@calcom/web:start:   - Local:        http://localhost:3000
@calcom/web:start: 
@calcom/web:start:  ✓ Ready in 2.1s
@calcom/web:start: Warning: data for page "/auth/setup" is 184 kB which exceeds the threshold of 128 kB, this amount of data can reduce performance.
@calcom/web:start: See more info here: https://nextjs.org/docs/messages/large-page-data
@calcom/web:start: 14:41:51:143 [ERROR] [redactError] Error:  {"name":"PrismaClientKnownRequestError","code":"P2022","clientVersion":"5.4.2","meta":{"column":"isPlatformManaged"}}
```

**Comment by diarpu** [comment]
Same problem here

```
@calcom/web:start: Warning: data for page "/auth/login" is 356 kB which exceeds the threshold of 128 kB, this amount of data can reduce performance.
@calcom/web:start: See more info here: https://nextjs.org/docs/messages/large-page-data
```

**Comment by krumware** [comment]
Please reopen on calcom/cal.com if this migration is still an issue. Thanks!
