### ISSUE TITLE
Cannot find module `/app/node_modules/@hookform/resolvers/zod/dist/zod`

### ISSUE THREAD

**Issue by adriaanvanrossum** [calcom/docker#79]
When following the instructions on the home page and running `docker-compose up --build -d` I get the following error from the logs in `docker logs calendso-docker_calendso_1 -f`:

```
+ /app/scripts/wait-for-it.sh database:5432 -- echo database is up
nc command is missing!
+ npx prisma migrate deploy
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "calendso", schema "public" at "database:5432"

65 migrations found in prisma/migrations

No pending migrations to apply.
+ yarn start
yarn run v1.22.17
$ next start
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
18:02:09.421 timeZoneName DEBUG [error] server side logged this: Error: Cannot find module '/app/node_modules/@hookform/resolvers/zod/dist/zod' 
18:02:09.434 timeZoneName INFO  [error] return props,  
{
  statusCode: 500,
  hasGetInitialPropsRun: true
}
react-i18next:: You will need to pass in an i18next instance by using initReactI18next
Error: Cannot find module '/app/node_modules/@hookform/resolvers/zod/dist/zod'
    at createEsmNotFoundErr (internal/modules/cjs/loader.js:929:15)
    at finalizeEsmResolution (internal/modules/cjs/loader.js:922:15)
    at resolveExports (internal/modules/cjs/loader.js:450:14)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.mod._resolveFilename (/app/node_modules/next/dist/build/webpack/require-hook.js:183:28)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.66615 (/app/.next/server/pages/getting-started.js:876:18) {
  code: 'MODULE_NOT_FOUND',
  path: '/app/node_modules/@hookform/resolvers/package.json'
}
```

I can log in with the credentials I have set. But get a 500 page when going to `/getting-started`.

**Comment by emrysal** [comment]
Hi @adriaanvanrossum - this was a temporary issue in main resolved by https://github.com/calcom/cal.com/pull/1681 - it should work now.

**Comment by adriaanvanrossum** [comment]
Thank you!
