### ISSUE TITLE
Dockerfile: calendso/apps/web/prisma missing in submodule

### ISSUE THREAD

**Issue by kettenbach-it** [calcom/docker#91]
This

```
COPY calendso/apps/web/prisma prisma
```

fail because in `https://github.com/calcom/cal.com/tree/main/apps/web` there is no prisma

**Comment by ospaarmann** [comment]
Same here when trying to build:

```
$ docker-compose up --build

Creating network "calendso-docker_stack" with the default driver
Creating volume "calendso-docker_database-data" with default driver
Pulling database (postgres:)...
latest: Pulling from library/postgres
8998bd30e6a1: Pull complete
8c57ecc00197: Pull complete
8b1aaa551482: Pull complete
409382316c26: Pull complete
3b2a428af099: Pull complete
e44b8e834aba: Pull complete
1372eb84c820: Pull complete
a5165dcf612e: Pull complete
7e45ff7cf799: Pull complete
0120f31c45d8: Pull complete
53086ac0b20d: Pull complete
1768b379179b: Pull complete
5824524f384b: Pull complete
Digest: sha256:156c50d4b6fe6ea4e4645ccdeabf54fedc59a561bfece047cdf4c26a42deab72
Status: Downloaded newer image for postgres:latest
Building calendso
[+] Building 2.9s (8/23)
 => [internal] load build definition from Dockerfile                                                                                                                                  0.0s
 => => transferring dockerfile: 1.41kB                                                                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                                                                     0.0s
 => => transferring context: 2B                                                                                                                                                       0.0s
 => [internal] load metadata for docker.io/library/node:14                                                                                                                            2.5s
 => [internal] load build context                                                                                                                                                     0.3s
 => => transferring context: 7.92MB                                                                                                                                                   0.3s
 => CANCELED [deps 1/5] FROM docker.io/library/node:14@sha256:b2c75df8c9706156c38b4f1f678d00e11cb2bfda09fc4ab6e36ec17ac9163865                                                        0.3s
 => => resolve docker.io/library/node:14@sha256:b2c75df8c9706156c38b4f1f678d00e11cb2bfda09fc4ab6e36ec17ac9163865                                                                      0.0s
 => => sha256:edf576a0611a8862b3ac5cc25b79aedd7b2f5a1a457ead352a467fa5b906d0f6 0B / 10.22MB                                                                                           0.3s
 => => sha256:57ad1991ad642f879ea12aacfd62d783237cf0a4f001f400452ddfe37c25ba3a 7.65kB / 7.65kB                                                                                        0.0s
 => => sha256:11cbe372cf332799e1339b2b8a04723e8224eb56d69212a1308d1df0da55eae2 0B / 43.17MB                                                                                           0.3s
 => => sha256:abc21f7f695aceaf60c5d2590b7acb0d3937aab7af8a9470dd74605632805610 0B / 3.87MB                                                                                            0.3s
 => => sha256:b2c75df8c9706156c38b4f1f678d00e11cb2bfda09fc4ab6e36ec17ac9163865 776B / 776B                                                                                            0.0s
 => => sha256:1024f34b5a187d90722434cf259739470de4b8688d6c70b7a583704664977124 2.21kB / 2.21kB                                                                                        0.0s
 => CACHED [deps 2/5] WORKDIR /calcom                                                                                                                                                 0.0s
 => CACHED [deps 3/5] COPY calendso/apps/web/package.json calendso/apps/web/yarn.lock ./                                                                                              0.0s
 => ERROR [deps 4/5] COPY calendso/apps/web/prisma prisma                                                                                                                             0.0s
------
 > [deps 4/5] COPY calendso/apps/web/prisma prisma:
------
failed to compute cache key: "/calendso/apps/web/prisma" not found: not found
ERROR: Service 'calendso' failed to build : Build failed
```

**Comment by kettenbach-it** [comment]
I think "yarn" needs to run before this COPY, since it installs prisma.

Can you try that?

**Comment by ospaarmann** [comment]
I tried running `yarn` before. Same result:

```
🤷 ❯ yarn
yarn install v1.22.17
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Saved lockfile.
✨  Done in 0.02s.
🤷 ❯ docker-compose up
Building calendso
[+] Building 2.7s (8/23)
 => [internal] load build definition from Dockerfile                                                                                                                                  0.0s
 => => transferring dockerfile: 37B                                                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                                                     0.0s
 => => transferring context: 2B                                                                                                                                                       0.0s
 => [internal] load metadata for docker.io/library/node:14                                                                                                                            1.6s
 => CANCELED [deps 1/5] FROM docker.io/library/node:14@sha256:b2c75df8c9706156c38b4f1f678d00e11cb2bfda09fc4ab6e36ec17ac9163865                                                        0.0s
 => => resolve docker.io/library/node:14@sha256:b2c75df8c9706156c38b4f1f678d00e11cb2bfda09fc4ab6e36ec17ac9163865                                                                      1.0s
 => => sha256:b2c75df8c9706156c38b4f1f678d00e11cb2bfda09fc4ab6e36ec17ac9163865 776B / 776B                                                                                            0.0s
 => [internal] load build context                                                                                                                                                     0.1s
 => => transferring context: 62.92kB                                                                                                                                                  0.1s
 => CACHED [deps 2/5] WORKDIR /calcom                                                                                                                                                 0.0s
 => CACHED [deps 3/5] COPY calendso/apps/web/package.json calendso/apps/web/yarn.lock ./                                                                                              0.0s
 => ERROR [deps 4/5] COPY calendso/apps/web/prisma prisma                                                                                                                             0.0s
------
 > [deps 4/5] COPY calendso/apps/web/prisma prisma:
------
failed to compute cache key: "/calendso/apps/web/prisma" not found: not found
ERROR: Service 'calendso' failed to build : Build failed
```

**Comment by clarkhacks** [comment]
Same issue here.

**Comment by danilokorber** [comment]
Don't know if this is the right approach, but I renamed calendso/apps/web/@prisma to calendso/apps/web/prisma and it worked (at least until the next issue).

**Comment by agustif** [comment]
Hey guys, we recently moved to a monorepo managed with turborepo. We're moving shared stuff out from web into the @calcom/packages folder.

Can you try changing for @calcom/packages/prisma instead?

**Comment by christianreiss** [comment]
Hey @agustif !

I am the one stepping out of the crowd here. I see that you, ugh, wrote text. Great!
But as the average "docker run" guys we are that solution(?) you proposed does not help us in any way.

Change what now? How? What's a @calcom/prisma? Alias link? To what now? calcom/packages/prisma?
Turborepo sound fast, tho! :-)

**Comment by saschafoerster** [comment]
I tried also in all described ways to install Cal.com. With our without docker. No success. 
There is no good description or documentation to get it actually running on your own hardware. Neither for production or development. Feels like the source code is open, but not the spirit. So I use https://easyappointments.org/ because the installation was... easy. But I hope you take this comment as an encouragement to make installation for everyone a breeze.

**Comment by kettenbach-it** [comment]
@saschafoerster @christianreiss 

Same here: docs are very unclear, codebase is a mess. Didn't get a container build, even as a pretty experienced developer

**Comment by nickandre10x** [comment]
So the issue seems to be in the Dockerfile line 4:
> COPY calendso/apps/web/prisma prisma

They recently moved the prisma directory and haven't updated this, so change it to:

> COPY calendso/apps/web/@prisma prisma

**Comment by saschafoerster** [comment]
@nickandre10x Changing @prisma just get you to the next issue #92 / #85, which is still unsolved either. :) Waiting, testing, error, waiting again.

**Comment by secfigo** [comment]
Please refer to the following comment to set up the software. Will share a setup with caddy/traefik soon. 

https://github.com/calcom/docker/issues/92#issuecomment-1073483062

**Comment by krumware** [comment]
Please retest with latest, dockerfile changes have been merged from https://github.com/calcom/docker/pull/86

**Comment by Silur** [comment]
It get past the topic of this issue, but halts at:
```
Step 8/37 : RUN yarn install
 ---> Running in b4142847a9f9
yarn install v1.22.17
[1/5] Validating package.json...
[2/5] Resolving packages...
error Couldn't find package "@calcom/ui@*" required by "@calcom/web@1.0.0" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find package "@calcom/config@*" required by "@calcom/web@1.0.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/opt/yarn-v1.22.17/lib/cli.js:721:66)
    at new MessageError (/opt/yarn-v1.22.17/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/opt/yarn-v1.22.17/lib/cli.js:36582:17)
    at Generator.throw (<anonymous>)
    at step (/opt/yarn-v1.22.17/lib/cli.js:310:30)
    at /opt/yarn-v1.22.17/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
The command '/bin/sh -c yarn install' returned a non-zero code: 1
```

Full process:
https://asciinema.org/a/gTUaYD984pt8UeW5U9EYKmH1h

**Comment by danilokorber** [comment]
> The main topic of this issue is gone, it finds prisma but halts at a yarn error.
> 
> ```
> Step 8/37 : RUN yarn install
>  ---> Running in b4142847a9f9
> yarn install v1.22.17
> [1/5] Validating package.json...
> [2/5] Resolving packages...
> error Couldn't find package "@calcom/ui@*" required by "@calcom/web@1.0.0" on the "npm" registry.
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> Error: Couldn't find package "@calcom/config@*" required by "@calcom/web@1.0.0" on the "npm" registry.
>     at MessageError.ExtendableBuiltin (/opt/yarn-v1.22.17/lib/cli.js:721:66)
>     at new MessageError (/opt/yarn-v1.22.17/lib/cli.js:750:123)
>     at PackageRequest.<anonymous> (/opt/yarn-v1.22.17/lib/cli.js:36582:17)
>     at Generator.throw (<anonymous>)
>     at step (/opt/yarn-v1.22.17/lib/cli.js:310:30)
>     at /opt/yarn-v1.22.17/lib/cli.js:323:13
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> The command '/bin/sh -c yarn install' returned a non-zero code: 1
> ```
> 
> Full process: https://asciinema.org/a/gTUaYD984pt8UeW5U9EYKmH1h

Same here

**Comment by krumware** [comment]
Looks like issues with the submodules. Working on updates

**Comment by krumware** [comment]
related issue in main repo: https://github.com/calcom/cal.com/issues/2305

**Comment by zomars** [comment]
> So the issue seems to be in the Dockerfile line 4:
> 
> > COPY calendso/apps/web/prisma prisma
> 
> They recently moved the prisma directory and haven't updated this, so change it to:
> 
> > COPY calendso/apps/web/@prisma prisma

Actually it should be changed to

```
COPY calendso/packages/prisma prisma
```

**Comment by JoeyFenny** [comment]
> Hey guys, we recently moved to a monorepo managed with turborepo. We're moving shared stuff out from web into the @calcom/packages folder.
> 
> Can you try changing for `@calcom/prisma`, this should be an alias link for `calcom/packages/prisma`?

Seems like these changes shouldn't have been merged into main if they were only half-done.

**Comment by krumware** [comment]
this was resolved
